[package]
name = "test_client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.28"
futures = "0.3"
serde_json = "1"
dcp_commons = {path="../dcp_commons"}
time = { version = "0.3", features = ["local-offset"] }
ratatui = "0.30"
crossterm = "0.29.0"
futures-util = "0.3.31"